program ::= port_setting agent_defination+ action_defination+ behavior_defination+ task_defination+ main_task

port_setting ::= "Port" ":" integer

/* Action */
action_defination ::= "Action" variable "(" formal_parameters? ")" ":" compound_statement

/* Agent */
agent_defination ::= "Agent" variable "(" formal_parameters? ")" ":" compound_statement

/* Behavior */
behavior_defination ::= "Behavior" variable "(" formal_parameters? ")" ":" compound_statement

/* Task */
task_defination ::= "Task" variable "(" formal_parameters? ")" ":" compound_statement

/* parameter */
formal_parameters ::= variable ( "," variable )*

/* TODO: Agent decalaration */
main_task ::= "Main" ":" compound_statement

compound_statement ::= statement_list

statement_list ::= statement ( ";" statement )*

statement ::= assignment_statement
            | empty

assignment_statement ::= variable "=" additive_expression

empty ::= 

/* expr: term ((PLUS | MINUS) term)**/
additive_expression ::= multiplicative_expression ( ( "+" | "-" ) multiplicative_expression )*

/* term: factor ((MUL | DIV) factor)* */
multiplicative_expression ::= primary_expression ( ( "*" | "/" | "%" ) primary_expression )*

/* factor :INTEGER 
           | PLUS factor
           | MINUS factor
           | LPAREN expr RPAREN
           | variable */
primary_expression ::= integer
                        | ( "+" | "-" ) primary_expression
                        | "(" additive_expression ")"
                        | variable

variable ::= [a-zA-Z] ( [a-zA-Z0-9] | "_" )*

integer ::= "0" | ( [1-9] [0-9]* )